### ISSUE TITLE
The tutorials currently do not have any form.

### ISSUE THREAD

**Issue by tdh8316** [Oceavos/PythonCourses#1]
현재 이 강좌들은 모두 서식 없는 텍스트(text/plain) 파일로 작성되어 있습니다.
이 강좌들을 마크다운을 사용해서 새롭게 올리면 어떨까요?

------------------------------
그리고 위에서 사칙연산을 했던 명령어도 파이썬 출력 명령어에 대입하여 사용이 가능하다. 예제를 보며 익혀보자.
```python
>>> print(3+4)
7
>>> print(4-3)
1
>>> print(3*4)
12
>>> print(6/3)
2
```

--------------------------------
https://github.com/Oceavos/PythonCourses/blob/3697fd6cdc4a815c5d4594dedca6d0c22b935c52/Korean_ver/2_Datatypes/Step_4_String_Function.py#L28
- 문자열에서 문자의 개수 세기 (count)
```python
>>> A = "Hello, World!"
>>> A.count('l')
```

--------------------------------
https://github.com/Oceavos/PythonCourses/blob/3697fd6cdc4a815c5d4594dedca6d0c22b935c52/Korean_ver/2_Datatypes/Step_8_Dictionary_datatype.py#L47
### 딕셔너리 사용

- Key를 이용해서 Value 값을 얻기
```python
>>> test = {'name' : 'SeongJin-Hong', 'Nationality' : 'Korea'}
>>> test['name']        # test 딕셔너리에 name 을 Key로 갖는 Value를 반환해달라
SeongJin-Hong
>>> test['Nationality']      # test 딕셔너리에 Nationality 를 Key로 갖는 Value를 반환해달라
Korea
```
>**딕셔너리를 만들때 똑같은 키가 겹치지 않도록 해야 합니다.**

**Comment by Oceavos** [comment]
조언 감사합니다! 
추후 올릴때는 꼭 마크다운을 이용해서 올리도록 하겠습니다.
